services:
  db:
    image: postgres:16-alpine
    container_name: socially_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socially
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: socially-app
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/socially
      DB_HOST: db
      DB_PORT: 5432
      BETTER_AUTH_SECRET: 0a919fcdd41aca7ef382b6f5b6d75fd7767e3516176c05d787b765770f00489b
      BETTER_AUTH_URL: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
